apiVersion: v1
kind: ReplicationController
metadata:
  name: helloworld-controller
  labels:
    app: helloworld
spec:
  replicas: 2
  selector:
    app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
      - name: docker-demo-v2
        image: codingspecialist/docker-demo-v2
        ports:
        - containerPort: 3000