apiVersion: v1
kind: Pod
metadata:
  name: nodehelloworld-com
  labels:
    app: helloworld
spec:
  containers:
  - name: k8s-demo
    image: codingspecialist/docker-demo-v2
    ports:
    - name: nodejs-port
      containerPort: 3000
